version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  ukws-admin:
    build: .
    environment:
      UKWS_ADMIN_DATABASE_USERNAME: postgres
      UKWS_ADMIN_DATABASE_PASSWORD: password
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ukws-admin
    ports:
      - "3000:3000"
    depends_on:
      - db