version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  ukws-admin:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    stdin_open: true
    tty: true
    volumes:
      - .:/ukws-admin
    ports:
      - "3000:3000"
    depends_on:
      - db
